### ISSUE TITLE
Technical paper - data set descriptions for SI

### ISSUE THREAD

**Issue by anerv** [anastassiavybornova/bike-node-planner#52]

**Comment by anastassiavybornova** [comment]
@anerv i know we talked about including data set specifications in the SI, but i'm thinking that this might be an overkill since all the technical specifications are already part of the github workflow, and we would in the end just be copy pasting stuff from there. so maybe drop this from the SI, and only include in the SI a more detailed commentary of Fyn?

**Comment by anastassiavybornova** [comment]
closing as agreed
